name: Pull request check

on:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check lua

  luacheck:
    runs-on: ubuntu-latest
    steps:
      - uses: lunarmodules/luacheck@v1.2.0
